<?php

namespace BRMainBundle\Repository;

/**
 * LightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LightRepository extends \Doctrine\ORM\EntityRepository
{
}
