<?php

namespace BRMainBundle\Repository;

/**
 * MatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatosRepository extends \Doctrine\ORM\EntityRepository
{
}
