<?php

namespace BRMainBundle\Repository;

/**
 * MatosTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatosTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
