<?php

namespace BRMainBundle\Repository;

/**
 * TransMatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransMatosRepository extends \Doctrine\ORM\EntityRepository
{
}
